import { extractedReceiptSchema, type ExtractedReceipt } from "@/domain/extraction";

export const mockJoetenReceipt: ExtractedReceipt = extractedReceiptSchema.parse({
  merchantName: "JOETEN SUSUPE",
  storeAddress: "Beach Road, Susupe, Saipan",
  branchClues: "Susupe",
  phone: null,
  purchasedAt: "2026-08-12T18:41:00+10:00",
  currency: "USD",
  subtotalCents: 4286,
  taxCents: 0,
  totalCents: 4286,
  items: [
    {
      rawDescription: "NISHIKI RICE 20LB",
      normalizedName: "Nishiki Premium Rice 20 lb",
      brand: "Nishiki",
      quantity: 1,
      packageSize: 20,
      unit: "lb",
      lineTotalCents: 2499,
      unitPriceCents: 125,
      discountCents: 0,
      barcode: null,
      confidence: {
        rawDescription: 0.94,
        normalizedName: 0.9,
        brand: 0.88,
        quantity: 0.93,
        packageSize: 0.91,
        unit: 0.9,
        lineTotalCents: 0.95,
        unitPriceCents: 0.8,
        barcode: 0.2,
      },
    },
    {
      rawDescription: "MG MILK GAL",
      normalizedName: "Meadow Gold Whole Milk",
      brand: "Meadow Gold",
      quantity: 1,
      packageSize: 1,
      unit: "unknown",
      lineTotalCents: 799,
      unitPriceCents: 799,
      discountCents: 0,
      barcode: null,
      confidence: {
        rawDescription: 0.81,
        normalizedName: 0.64,
        brand: 0.58,
        quantity: 0.9,
        packageSize: 0.45,
        unit: 0.4,
        lineTotalCents: 0.92,
        unitPriceCents: 0.7,
        barcode: 0.1,
      },
    },
    {
      rawDescription: "SPAM CLASSIC 12OZ",
      normalizedName: "SPAM Classic",
      brand: "SPAM",
      quantity: 2,
      packageSize: 12,
      unit: "oz",
      lineTotalCents: 778,
      unitPriceCents: 32,
      discountCents: 0,
      barcode: "037600005559",
      confidence: {
        rawDescription: 0.92,
        normalizedName: 0.91,
        brand: 0.94,
        quantity: 0.66,
        packageSize: 0.88,
        unit: 0.9,
        lineTotalCents: 0.9,
        unitPriceCents: 0.84,
        barcode: 0.86,
      },
    },
    {
      rawDescription: "MARU 5PK CHKN",
      normalizedName: "Maruchan Chicken Ramen",
      brand: "Maruchan",
      quantity: 1,
      packageSize: 5,
      unit: "count",
      lineTotalCents: 210,
      unitPriceCents: 42,
      discountCents: 0,
      barcode: null,
      confidence: {
        rawDescription: 0.7,
        normalizedName: 0.61,
        brand: 0.6,
        quantity: 0.8,
        packageSize: 0.55,
        unit: 0.74,
        lineTotalCents: 0.57,
        unitPriceCents: 0.5,
        barcode: 0.05,
      },
    },
  ],
  confidence: {
    merchantName: 0.93,
    storeAddress: 0.71,
    purchasedAt: 0.68,
    currency: 0.97,
    totalCents: 0.94,
  },
});

export function getMockExtraction(): ExtractedReceipt {
  return mockJoetenReceipt;
}
